### ISSUE TITLE
[BUG] AUC Calculation during fit() makes process run out of memory

### ISSUE THREAD

**Issue by shoyasaxa** [NVIDIA-Merlin/HugeCTR#258]
**Describe the bug**
When the `fit()` function on a DLRM model tries to calculate AUC on the validation set, the process runs out of memory. The stack trace is below. 

```
[10d20h20m60s][HUGECTR][INFO]: Iter: 2300 Time(100 iters): 4.072998s Loss: 0.219250 lr:0.000029
[10d20h20m60s][HUGECTR][INFO]: Evaluation, AUC: 0.925024
[10d20h20m60s][HUGECTR][INFO]: Eval Time for 4 iters: 0.001988s
[10d20h20m11s][HUGECTR][INFO]: Iter: 2400 Time(100 iters): 4.306464s Loss: 0.171515 lr:0.000030
terminate called after throwing an instance of 'HugeCTR::internal_runtime_error'
  what():  [HCDEBUG][ERROR] Runtime error: out of memory /var/tmp/HugeCTR/HugeCTR/src/metrics.cu:461 

[jupyter-notebook] *** Process received signal ***
[jupyter-notebook] Signal: Aborted (6)
[jupyter-notebook] Signal code:  (-6)
[jupyter-notebook] [ 0] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7f9433b05210]
[jupyter-notebook] [ 1] /usr/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f9433b0518b]
[jupyter-notebook] [ 2] /usr/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f9433ae4859]
[jupyter-notebook] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x9e911)[0x7f9419ab2911]
[jupyter-notebook] [ 4] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa38c)[0x7f9419abe38c]
[jupyter-notebook] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa9369)[0x7f9419abd369]
[jupyter-notebook] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(__gxx_personality_v0+0x2a1)[0x7f9419abdd21]
[jupyter-notebook] [ 7] /usr/lib/x86_64-linux-gnu/libgcc_s.so.1(+0x10bef)[0x7f94199c7bef]
[jupyter-notebook] [ 8] /usr/lib/x86_64-linux-gnu/libgcc_s.so.1(_Unwind_Resume+0x12a)[0x7f94199c85aa]
[jupyter-notebook] [ 9] /usr/local/hugectr/lib/libhuge_ctr_shared.so(_ZN7HugeCTR7metrics3AUCIfE24_finalize_metric_per_gpuEi+0x10f1)[0x7f9430f469d1]
[jupyter-notebook] [10] /usr/local/hugectr/lib/libhuge_ctr_shared.so(+0x7e9342)[0x7f9430f47342]
[jupyter-notebook] [11] /usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x1a78e)[0x7f94199ec78e]
[jupyter-notebook] [12] /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x9609)[0x7f9433aa5609]
[jupyter-notebook [13] /usr/lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7f9433be1293]
[jupyter-notebook] *** End of error message ***
Aborted (core dumped)
```

This seems to only happen when I use multiple GPUs (I am using 4). When I try to `fit()` with only 1 GPU, this problem doesn't seem to occur. I am using `Tesla V100-SXM2-16GB`'s. 

It is also interesting to note that the validation seems to work for some number of mini batch iterations, before failing. I have tried to reduce the number of batch sizes for evaluation to something extremely small like 4 for `max_eval_batches` and 100 for `batchsize_eval` in the solver instantiation. However, this issue persists presumably on the `finalize_metric_per_gpu` step from the stack trace. 

**Expected behavior**
The AUC calculation should not make the process run out of memory when using multiple GPUs.

**Environment (please complete the following information):**
Using Docker Image built from `nvcr.io/nvidia/merlin/merlin-training:21.09`

**Comment by zehuanw** [comment]
Thank you for your feedback! @minseokl to help on it.

**Comment by viswa-nvidia** [comment]
Minseok>> 
The AUC issue was fixed by [this MR](https://gitlab-master.nvidia.com/dl/hugectr/hugectr/-/merge_requests/575) a few months ago. Thus, 22.04 already includes it. We may just have forgotten to close the public issue.
I think the reason why [@Joey Wang](https://nvidia.slack.com/team/U8YS4TWRZ) put it to P0 was because it was from the customer Peloton.  There was an email thread on it, which included [@Even Oldridge](https://nvidia.slack.com/team/UGWJKS08H) and [@Kingsley Liu](https://nvidia.slack.com/team/U017D5E4K7D) I just forwarded the email thread to you JFYI.
